# Form implementation generated from reading ui file '.\uifile\admin.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Admin_Form(object):
    def setupUi(self, Admin_Form):
        Admin_Form.setObjectName("Admin_Form")
        Admin_Form.resize(700, 350)
        self.request_table = QtWidgets.QTableWidget(parent=Admin_Form)
        self.request_table.setGeometry(QtCore.QRect(0, 0, 700, 290))
        self.request_table.setObjectName("request_table")
        self.request_table.setColumnCount(6)
        self.request_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.request_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.request_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.request_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.request_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.request_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.request_table.setHorizontalHeaderItem(5, item)

        self.retranslateUi(Admin_Form)
        QtCore.QMetaObject.connectSlotsByName(Admin_Form)

    def retranslateUi(self, Admin_Form):
        _translate = QtCore.QCoreApplication.translate
        Admin_Form.setWindowTitle(_translate("Admin_Form", "Окно админа"))
        item = self.request_table.horizontalHeaderItem(0)
        item.setText(_translate("Admin_Form", "id заявки"))
        item = self.request_table.horizontalHeaderItem(1)
        item.setText(_translate("Admin_Form", "id пользователя"))
        item = self.request_table.horizontalHeaderItem(2)
        item.setText(_translate("Admin_Form", "Имя заявки"))
        item = self.request_table.horizontalHeaderItem(3)
        item.setText(_translate("Admin_Form", "Статус"))
        item = self.request_table.horizontalHeaderItem(4)
        item.setText(_translate("Admin_Form", "Приоритет"))
        item = self.request_table.horizontalHeaderItem(5)
        item.setText(_translate("Admin_Form", "Действие"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Admin_Form = QtWidgets.QWidget()
    ui = Ui_Admin_Form()
    ui.setupUi(Admin_Form)
    Admin_Form.show()
    sys.exit(app.exec())
