# Form implementation generated from reading ui file '.\history.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_History_Form(object):
    def setupUi(self, History_Form):
        History_Form.setObjectName("History_Form")
        History_Form.resize(600, 315)
        self.history_table = QtWidgets.QTableWidget(parent=History_Form)
        self.history_table.setGeometry(QtCore.QRect(0, 0, 600, 270))
        self.history_table.setObjectName("history_table")
        self.history_table.setColumnCount(4)
        self.history_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_table.setHorizontalHeaderItem(3, item)
        self.exit_but = QtWidgets.QPushButton(parent=History_Form)
        self.exit_but.setGeometry(QtCore.QRect(240, 280, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.exit_but.setFont(font)
        self.exit_but.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.exit_but.setObjectName("exit_but")

        self.retranslateUi(History_Form)
        QtCore.QMetaObject.connectSlotsByName(History_Form)

    def retranslateUi(self, History_Form):
        _translate = QtCore.QCoreApplication.translate
        History_Form.setWindowTitle(_translate("History_Form", "История"))
        item = self.history_table.horizontalHeaderItem(0)
        item.setText(_translate("History_Form", "Id заявки"))
        item = self.history_table.horizontalHeaderItem(1)
        item.setText(_translate("History_Form", "Тип заявки"))
        item = self.history_table.horizontalHeaderItem(2)
        item.setText(_translate("History_Form", "Старый статус"))
        item = self.history_table.horizontalHeaderItem(3)
        item.setText(_translate("History_Form", "Новый статус"))
        self.exit_but.setText(_translate("History_Form", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    History_Form = QtWidgets.QWidget()
    ui = Ui_History_Form()
    ui.setupUi(History_Form)
    History_Form.show()
    sys.exit(app.exec())
