# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login_Form(object):
    def setupUi(self, Login_Form):
        Login_Form.setObjectName("Login_Form")
        Login_Form.resize(207, 306)
        self.label = QtWidgets.QLabel(parent=Login_Form)
        self.label.setGeometry(QtCore.QRect(40, 60, 120, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Login_Form)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 120, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.login_line = QtWidgets.QLineEdit(parent=Login_Form)
        self.login_line.setGeometry(QtCore.QRect(40, 100, 120, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.login_line.setFont(font)
        self.login_line.setObjectName("login_line")
        self.pas_line = QtWidgets.QLineEdit(parent=Login_Form)
        self.pas_line.setGeometry(QtCore.QRect(40, 180, 120, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pas_line.setFont(font)
        self.pas_line.setObjectName("pas_line")
        self.pushButton = QtWidgets.QPushButton(parent=Login_Form)
        self.pushButton.setGeometry(QtCore.QRect(50, 240, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Login_Form)
        QtCore.QMetaObject.connectSlotsByName(Login_Form)

    def retranslateUi(self, Login_Form):
        _translate = QtCore.QCoreApplication.translate
        Login_Form.setWindowTitle(_translate("Login_Form", "Окно входа"))
        self.label.setText(_translate("Login_Form", "Логин"))
        self.label_2.setText(_translate("Login_Form", "Пароль"))
        self.pushButton.setText(_translate("Login_Form", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_Form = QtWidgets.QWidget()
    ui = Ui_Login_Form()
    ui.setupUi(Login_Form)
    Login_Form.show()
    sys.exit(app.exec())
