# Form implementation generated from reading ui file '.\user.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_User_Form(object):
    def setupUi(self, User_Form):
        User_Form.setObjectName("User_Form")
        User_Form.resize(260, 238)
        self.label = QtWidgets.QLabel(parent=User_Form)
        self.label.setGeometry(QtCore.QRect(50, 50, 160, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.type_line = QtWidgets.QLineEdit(parent=User_Form)
        self.type_line.setGeometry(QtCore.QRect(50, 80, 160, 25))
        self.type_line.setObjectName("type_line")
        self.add_req = QtWidgets.QPushButton(parent=User_Form)
        self.add_req.setGeometry(QtCore.QRect(70, 150, 120, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.add_req.setFont(font)
        self.add_req.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.add_req.setObjectName("add_req")
        self.view_histor = QtWidgets.QPushButton(parent=User_Form)
        self.view_histor.setGeometry(QtCore.QRect(70, 190, 120, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.view_histor.setFont(font)
        self.view_histor.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.view_histor.setObjectName("add_req_2")

        self.retranslateUi(User_Form)
        QtCore.QMetaObject.connectSlotsByName(User_Form)

    def retranslateUi(self, User_Form):
        _translate = QtCore.QCoreApplication.translate
        User_Form.setWindowTitle(_translate("User_Form", "Окно пользователя"))
        self.label.setText(_translate("User_Form", "Введите тип заявки"))
        self.add_req.setText(_translate("User_Form", "Создать заявку"))
        self.view_histor.setText(_translate("User_Form", "История"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    User_Form = QtWidgets.QWidget()
    ui = Ui_User_Form()
    ui.setupUi(User_Form)
    User_Form.show()
    sys.exit(app.exec())
